# Generated by Django 5.2.6 on 2026-07-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_alter_materialoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialoperation',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
    ]
